read_properties:
  fields:
    properties:
      required: true
      example: "AllOutWatTemHi, AllOutWatTemLo"
      selector:
        text:
          multiple: true
    config_entry_id:
      selector:
        config_entry:
          integration: greehp
